### ISSUE TITLE
Update tardis test to use Angstroms

### ISSUE THREAD

**Issue by mrakitin** [bluesky/hklpy#106]
https://github.com/bluesky/hklpy/blob/1ce145a4de8c3643a0df224c19eea309a84a8fe1/hkl/tests/test_tardis.py#L60
and
https://github.com/bluesky/hklpy/blob/1ce145a4de8c3643a0df224c19eea309a84a8fe1/hkl/tests/test_tardis.py#L90

Observed it with @cmazzoli while testing the new version of hklpy 0.3.15 at NSLS-II CSX.

**Comment by prjemian** [comment]
Since tardis uses soft X-rays, a wavelength of 1.33 **Angstrom** (energy of 9.31 keV) is not credible.  Wavelength was specified in **nm** here.  An energy of 931 **eV** is more realistic (0.13317314715359827 Angstrom).  Check the lattice parameters for nm or Angstrom.

This change is in response to #17 & #43 which was merged in PR #44.
