### ISSUE TITLE
document how to acknowledge and credit contributions

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#169]
When code is contributed by the community, cite the contributor(s) in the docstring of each contribution.  This builds community!

@rodolakis:  Thanks for the tip!

**Comment by prjemian** [comment]
Some discussion about whether to put acknowledgements into the source code docstrings (it tends to personalize the code) or to acknowledge in the release notes.  _In the release notes_ is a popular choice.  Also note in the pull requests and issues.

**Comment by tacaswell** [comment]
I'm modestly :-1: on doing this in docstrings.

To be very clear, I think making sure people get, and feel like they get, recognition for their contributions!  I also think we need to be better about identifying and crediting work that does not result in a (code) commit.   I just do not think `__doc__` is the right place to do it.

On the user side, a very common way to access the docstrings is via `? my_function` in the service of Getting Things Done.  To that end, I think we should keep the contents of `__doc__` to only the information in service of that.

From the developer / community side I am a bit worried about the consequences of what @prjemian calls personalizing the code.   One thing that I think is important for community code projects a sense of collective ownership of the code.  If we have a collection of functions some of which are "Tom's functions" and some of which are "Pete's functions", then we effectively have 2 single-developer libraries that just happen to be co-located!  

As a developer I am not sure I want to put my name on any given function because that will be seen by some as an invitation to send emails asking for support directly to me.  This isn't great for me (because signing up for open-ended user support is a daunting!), is not great for the user (as given the previous point I may be too busy to respond or have moved on to other work), and not great for the community (as there is a lot of valuable work being done in fundamentally private channels!  If one user has a problem then there exists another user with the same problem, if the first user got their question answered in email the second user can _never_ find that and well have to re-ask). 

Another practical concern is if there is an existing function and then it gets extended....what is the threshold for adding a new name?

This is touching on two Hard Problems in open source software with how it intersects with the (quasi)academic world: community building and how ensure that software development work is credited (for career progression) 

I propose changing the issue title to "document how acknowledge and credit contributions".

**Comment by mrakitin** [comment]
I like the way the conda-forge community recognizes the contributors based on their commits/PRs, such as in this project: https://github.com/conda-forge/conda-smithy/releases. Maybe that approach can be adopted here.

**Comment by prjemian** [comment]
@mrakitin: Good idea, adding list of contributors/authors to each release.

**Comment by prjemian** [comment]
no further work here
